var barray = [{"Dish":"Amy","price":42,"cuisine":"Yemen","vegan":0,"vegetarian":1,"pescatarian":0,"recipe":[{}]},
{"Dish":"Dennis","price":40,"cuisine":"Philippines","vegan":1,"vegetarian":0,"pescatarian":0,"recipe":[{}]},
{"Dish":"Rachel","price":22,"cuisine":"Peru","vegan":1,"vegetarian":0,"pescatarian":1,"recipe":[{},{},{},{},{}]},
{"Dish":"Philip","price":29,"cuisine":"Germany","vegan":1,"vegetarian":0,"pescatarian":0,"recipe":[{}]},
{"Dish":"Phillip","price":36,"cuisine":"Russia","vegan":0,"vegetarian":0,"pescatarian":0,"recipe":[{},{},{},{},{}]},
{"Dish":"Sandra","price":12,"cuisine":"China","vegan":1,"vegetarian":1,"pescatarian":1,"recipe":[{},{},{}]},
{"Dish":"Terry","price":34,"cuisine":"Czech Republic","vegan":1,"vegetarian":1,"pescatarian":0,"recipe":[{},{},{}]},
{"Dish":"Rice","price":12,"cuisine":"China","vegan":1,"vegetarian":0,"pescatarian":0,"recipe":[{},{},{},{}]},
{"Dish":"Harold","price":6,"cuisine":"Serbia","vegan":0,"vegetarian":1,"pescatarian":1,"recipe":[{},{}]},
{"Dish":"Rice","price":10,"cuisine":"China","vegan":0,"vegetarian":0,"pescatarian":1,"recipe":[{},{},{},{}]},
{"Dish":"Andrew","price":17,"cuisine":"Togo","vegan":0,"vegetarian":1,"pescatarian":0,"recipe":[{},{},{},{}]},
{"Dish":"Tacos","price":10,"cuisine":"Portugal","vegan":0,"vegetarian":1,"pescatarian":1,"recipe":[{},{},{},{}]},
{"Dish":"Lo Mein","price":37,"cuisine":"China","vegan":0,"vegetarian":0,"pescatarian":0,"recipe":[{},{},{},{}]},
{"Dish":"Croissant","price":40,"cuisine":"France","vegan":1,"vegetarian":1,"pescatarian":0,"recipe":[{},{},{}]},
{"Dish":"Rice","price":7,"cuisine":"Poland","vegan":1,"vegetarian":0,"pescatarian":0,"recipe":[{},{},{},{},{}]},
{"Dish":"Noodles","price":3,"cuisine":"China","vegan":1,"vegetarian":1,"pescatarian":1,"recipe":[{},{},{}]},
{"Dish":"Peter","price":25,"cuisine":"Japan","vegan":0,"vegetarian":0,"pescatarian":1,"recipe":[{},{},{}]},
{"Dish":"Andrea","price":32,"cuisine":"Indonesia","vegan":0,"vegetarian":1,"pescatarian":0,"recipe":[{}]},
{"Dish":"Joan","price":50,"cuisine":"Indonesia","vegan":1,"vegetarian":0,"pescatarian":1,"recipe":[{},{},{},{}]},
{"Dish":"Nicole","price":28,"cuisine":"Philippines","vegan":1,"vegetarian":1,"pescatarian":0,"recipe":[{},{}]}];